spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: #당신의 클라이언트 ID
            client-secret: #당신의 클라이언트 시크릿
            scope:
              - email
              - profile
          facebook:
            client-id: #당신의 클라이언트 ID
            client-secret: #당신의 클라이언트 ID
            scope:
              - email
              - profile