spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: #Client_Id
            client-secret: #Client_secret
            scope:
              - email
              - profile
          facebook:
            client-id: #Client_Id
            client-secret: #Client_secret
            scope:
              - email
              - public_profile
#          kakao:
#            client-id: #Client_Id
#            authorization-grant-type: authorization-code
#            scope:
#              - profile_nickname
#              - account_email
#            client-name: Kakao
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
# 왠지는 모르겠지만 잘 안돼요 그래서 properties로 이전
#          naver:
#            client-id: #당신의 클라이언트 ID
#            client-secret: #당신의 클라이언트 ID
#            scope:
#              - name
#              - email
#            client-name: Naver
#            authorization-grant-type: authorization-code
#            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}" #http://localhost:8080/login/oauth2/code/naver
#
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response